version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - config.env
    ports:
      - "5432:5432"

  backend:
    build: 
      context: .
    ports:
      - "9000:8000"
    env_file:
      - config.env
    volumes:
      - .:/app
    container_name: backend
    depends_on:
      - postgres
    command: "alembic upgrade head && uvicorn src.app:app --host 0.0.0.0 --port 8000"