version: '3.9'
services:
  backend:
    build: 
      context: .
    ports:
      - "9000:8000"
    env_file:
      - ./config/conf.env
    volumes:
      - .:/app
    container_name: backend
    command: /bin/bash -c "alembic upgrade head && uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload"

  kafka:
    image: bitnami/kafka:latest
    env_file:
      - ./config/conf.env
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
    ports:
      - "9092:9092"
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"