"""initial migrations

Revision ID: 9c99d8ee40ab
Revises: 
Create Date: 2024-12-03 21:34:21.856076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c99d8ee40ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cargo_type', sa.String(length=32), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_date'), 'tariff', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariff_date'), table_name='tariff')
    op.drop_table('tariff')
    # ### end Alembic commands ###
